### ISSUE TITLE
Syntax coloring in list comprehension expressions

### ISSUE THREAD

**Issue by jmayr71** [atom-haskell/language-haskell#113] opened 2017-12-11 22:11 UTC
Syntax coloring for list comprehension expressions is not working properly if there is a single entry in the expression part without any other characters like spaces or brackets.

Example: head ([x|(x,y) <- zip [0..] $ map (fib) [0..], n==y || y > n])

Coloring stops after x|

If a space or other characters are added coloring works again correctly.

Example: head ([ x |(x,y) <- zip [0..] $ map (fib) [0..], n==y || y > n]) is colored correctly.

**Comment by lierdakil** [comment] 2017-12-13 06:36
Duplicate of https://github.com/atom-haskell/language-haskell/issues/86. See also [what GHC documentation has to say on the topic](https://downloads.haskell.org/~ghc/8.2.1/docs/html/users_guide/glasgow_exts.html?highlight=#quasi-quotes-list-comprehension-ambiguity)

**Closed by lierdakil** 2017-12-13 06:36 UTC
