### ISSUE TITLE
Wrong syntax highlighting after first "data" declaration

### ISSUE THREAD

**Issue by ArtemyB** [atom-haskell/language-haskell#42] opened 2015-07-30 15:35 UTC
(I'm not sure, that it isn't only my problem, so sorry in this case. :) )
**With "data":** 
![2015-07-30_18-24-16](https://cloud.githubusercontent.com/assets/8839749/8987198/79d7f3e6-36e8-11e5-984d-80698cd2ebcc.png)
**Without "data":**
![2015-07-30_18-27-16](https://cloud.githubusercontent.com/assets/8839749/8987233/a5294716-36e8-11e5-80d1-7f617bce5492.png)

I don't know, maybe it's ok, but in other syntax highlightings ("haskell-grammar" for Atom, "SublimeHaskell" for Sublime Text) there are no such differences.

**Comment by lierdakil** [comment] 2015-07-30 20:01
![image](https://cloud.githubusercontent.com/assets/7275622/8993584/93169e04-370e-11e5-9e5b-5bd6060c9f28.png)

As you can see, I can't reproduce it on my end. Could you specify Atom version, language-haskell version you're running, and platform you're running on?

**Comment by ArtemyB** [comment] 2015-07-30 23:01
Atom version: 1.0.3
language-haskell version: 1.2.0
OS: Windows 8.1
But I was able to get right syntax highlighting by just deleting left tabs for all code after `module` declaration. You can see it on screenshots:
![2015-07-31_01-52-46](https://cloud.githubusercontent.com/assets/8839749/8997162/f29f273e-3726-11e5-8d35-5f105543159a.png)
![2015-07-31_01-54-11](https://cloud.githubusercontent.com/assets/8839749/8997173/12d47040-3727-11e5-95e3-a95a7c430292.png)
Maybe it's again only on my side. But now it's not a problem.

**Comment by lierdakil** [comment] 2015-07-31 10:29
Found what caused it. Apparently a typo snuck in. I don't usually indent type declarations, so it flew under the radar. Should be fixed with 1.2.1. Thanks for finding this!

**Closed by lierdakil** 2015-07-31 10:29 UTC
Labels: bug

**Comment by ArtemyB** [comment] 2015-07-31 11:30
Yes, now it's ok. Thanks for your work at all!
